name: google_maps_extractor
description: A comprehensive Flutter package for extracting coordinates and metadata from Google Maps URLs.
version: 1.0.2
repository: https://github.com/mohamedelbaiomy/google_maps_extractor
homepage: https://github.com/mohamedelbaiomy/google_maps_extractor

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
